INSERT INTO USERS (FIRST_NAME, LAST_NAME, LOGIN, PASSWORD) VALUES ('Fionna', 'Westbury','fwestbury','frites');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, LOGIN, PASSWORD) VALUES ('Clémentine', 'Bouillaud','cbouillaud','gauffre');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, LOGIN, PASSWORD) VALUES ('David', 'Thibau','dthibau','tortilla');

INSERT INTO ITEM (AUTHOR, QUANTITY, RELEASE_DATE, TITLE) VALUES ('Fionna', 3,'2022-10-07','le gras cest la vie');
INSERT INTO ITEM (AUTHOR, QUANTITY, RELEASE_DATE, TITLE) VALUES ('Clémentine', 1,'2022-10-07','vive les gauffres');
INSERT INTO ITEM (AUTHOR, QUANTITY, RELEASE_DATE, TITLE) VALUES ('David', 2,'2022-10-07','cours de java avancé');

INSERT INTO DVD (ID, DURATION, TYPE) VALUES (2, 30,'BLUERAY');

INSERT INTO CD (ID, DURATION, NB_TITLE) VALUES (1, 30,4);

INSERT INTO BOOK (ID, ISBN) VALUES (3, '9788175257665');

INSERT INTO BORROW (BORROW_DATE, RETURN_DATE, USER_ID) VALUES ('2022-10-07', NULL, 1);

INSERT INTO BORROW_ITEMS (BORROW_ID, ITEMS_ID) VALUES (1,2);